//! Phase 49.3 Plan 02 (D-05/D-06, RESEARCH Pitfall 1/2): the root-scope
//! write-only `.env` secret writer for the Gateway screen's secret-bearing
//! fields (chat platform bot tokens, the REST API server key).
//!
//! # Why this exists — the gateway is a separate OS process
//!
//! `resolve_token`/`resolve_token_with_env` (`runner.rs:2588-2616`) and the
//! REST API server's `std::env::var("IRONHERMES_API_SERVER_KEY")`
//! (`ironhermes-restgw/src/api_server/mod.rs:135`) only ever see a literal
//! `config.yaml` field (plaintext — rejected by the write-only contract) or a
//! real process env var, populated at gateway startup by
//! `dotenvy::from_path(Config::env_path())`
//! (`ironhermes-cli/src/main.rs:1799`). `tools.credentials`/vault's root
//! tiers are provably invisible to that separately-spawned process — a write
//! through the tools-credentials vault primitive would show "present" in
//! this UI while the gateway silently never resolves it. This module is the
//! one seam D-05/D-06 route their secrets through instead.
//!
//! # Two scope arms, one seam
//!
//! `ConfigScope::Root` targets `Config::env_path()` directly, reusing
//! `profile_api`'s already path-generic `read_env_keys`/
//! `write_env_atomic_0600` plus a small parallel `render_root_env_with_stamp`
//! (RESEARCH Open Question 2's recommended shape — a small twin, not a widen
//! of the heavily-tested `render_profile_env_with_stamp`).
//! `ConfigScope::Profile(name)` delegates unchanged to
//! `profile_api::save_profile_key_impl_with_stamp` — the existing
//! profile-scope writer needs no change here.
//!
//! # Write-only (D-06 carried forward)
//!
//! [`set_gateway_secret`] never returns the value it wrote — only presence
//! metadata ([`GatewaySecretAck`]). A secret value never round-trips back to
//! the browser through this surface.

use dioxus::prelude::*;
#[cfg(not(target_arch = "wasm32"))]
use secrecy::{ExposeSecret, SecretString};
use serde::{Deserialize, Serialize};

use crate::server::tools_config_api::ConfigScope;

/// Write-only acknowledgement — presence metadata only, NEVER the value
/// (D-06). The browser learns "this key is now set", nothing else.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GatewaySecretAck {
    pub key_name: String,
    pub present: bool,
}

/// Line 1 of every root-scope `.env` this writer generates — the root-scope
/// twin of `profile_api::PROFILE_ENV_PROVENANCE_PREFIX`. Kept as a `#`-
/// prefixed comment so it is inert to every `.env` parser (verified by
/// [`render_root_env_with_stamp`]'s own round-trip check).
#[cfg(not(target_arch = "wasm32"))]
const GATEWAY_ENV_PROVENANCE_PREFIX: &str =
    "# Generated by iron_hermes_ui Gateway secret writer (Phase 49.3) for scope \"";

/// Renders a root-scope `.env` file body — the root-scope twin of
/// `profile_api::render_profile_env_with_stamp`, parameterized with a scope
/// label per RESEARCH Open Question 2's recommendation (a small parallel fn,
/// never a widen of the profile fn's own signature). Every value is
/// single-quoted via the shared `ironhermes_core::dotenv_write::quote_env_value`
/// (the same primitive `render_profile_env_with_stamp` delegates to), and the
/// render proves itself via `verify_env_round_trip` before returning — a
/// write whose rendered bytes cannot be parsed back to exactly `entries` is
/// refused (T-49.3-02-02).
#[cfg(not(target_arch = "wasm32"))]
fn render_root_env_with_stamp(
    scope_label: &str,
    entries: &[(String, String)],
) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(GATEWAY_ENV_PROVENANCE_PREFIX);
    out.push_str(scope_label);
    out.push_str("\"\n");
    out.push_str(
        "# Secrets for the separately-spawned gateway process — dotenvy loads this file\n",
    );
    out.push_str(
        "# at gateway startup (config.yaml and the credentials vault are invisible to\n",
    );
    out.push_str("# that process; this .env is the only channel — 49.3-RESEARCH.md Pitfall 1).\n");
    for (key, value) in entries {
        out.push_str(key);
        out.push('=');
        out.push_str(&ironhermes_core::dotenv_write::quote_env_value(value));
        out.push('\n');
    }
    ironhermes_core::dotenv_write::verify_env_round_trip(&out, entries).map_err(|e| e.to_string())?;
    Ok(out)
}

/// Fail-closed write gate — same flag and error string every other
/// browser-reachable config/credential write surface in this crate enforces
/// (`profile_api::check_profile_write_gate`, `platform_config_api::
/// check_buzz_write_gate`). Always reads a FRESH ROOT `Config::load()`
/// regardless of the scope being edited (T-49.3-02-04). Pure(-ish) and
/// directly unit-testable.
#[cfg(not(target_arch = "wasm32"))]
fn check_gateway_write_gate() -> Result<(), String> {
    let root_config =
        ironhermes_core::config::Config::load().map_err(|e| format!("Config load failed: {e}"))?;
    if !root_config.security.web_config_write_enabled {
        return Err("Config writes are disabled".to_string());
    }
    Ok(())
}

/// The pure(-ish), disk-backed core of [`set_gateway_secret`]. Validates the
/// key name (T-49.3-02-01) and value BEFORE any gate check or disk I/O — a
/// rejected name/value touches nothing on disk, mirroring
/// `save_profile_key_impl_with_stamp`'s own discipline. Never routes through
/// the tools-credentials vault write primitive (RESEARCH Pitfall 1) — only
/// the scoped `.env` reaches the gateway process.
#[cfg(not(target_arch = "wasm32"))]
fn set_gateway_secret_impl(
    scope: &ConfigScope,
    key_name: &str,
    value: &SecretString,
) -> Result<GatewaySecretAck, String> {
    crate::server::profile_api::validate_key_name(key_name)
        .map_err(|e| format!("invalid key name: {e}"))?;
    crate::server::profile_api::validate_key_value(value.expose_secret())
        .map_err(|e| format!("invalid value for key '{key_name}': {e}"))?;
    check_gateway_write_gate()?;

    match scope {
        ConfigScope::Root => {
            let env_path = ironhermes_core::config::Config::env_path();
            let mut env_map = crate::server::profile_api::read_env_keys(&env_path)
                .map_err(|e| format!("read root .env: {e}"))?;
            env_map.insert(key_name.to_string(), value.expose_secret().to_string());

            let mut entries: Vec<(String, String)> = env_map.into_iter().collect();
            entries.sort_by(|a, b| a.0.cmp(&b.0));

            let contents = render_root_env_with_stamp("root", &entries)?;
            crate::server::profile_api::write_env_atomic_0600(&env_path, &contents)
                .map_err(|e| format!("write .env: {e}"))?;

            Ok(GatewaySecretAck {
                key_name: key_name.to_string(),
                present: true,
            })
        }
        ConfigScope::Profile(name) => {
            let row = crate::server::profile_api::save_profile_key_impl_with_stamp(
                name, key_name, value, None,
            )?;
            Ok(GatewaySecretAck {
                key_name: row.name,
                present: true,
            })
        }
    }
}

/// Write (create or replace) one gateway secret in the scope's `.env` —
/// `ConfigScope::Root` for D-05 (`IRONHERMES_API_SERVER_KEY`) and D-06's
/// chat-platform bot tokens when stored at root, `ConfigScope::Profile(name)`
/// for the same secrets scoped to a bot-mode profile. Fail-closed behind
/// `security.web_config_write_enabled` (T-49.3-02-04). The value is wrapped
/// in `SecretString` the moment it crosses the wasm/native boundary — before
/// it can reach any `Debug`-deriving struct — and is never echoed back in
/// the return, an error message, or a `tracing` call (D-13/D-06).
#[server]
pub async fn set_gateway_secret(
    scope: ConfigScope,
    key_name: String,
    value: String,
) -> Result<GatewaySecretAck, ServerFnError> {
    #[cfg(not(target_arch = "wasm32"))]
    {
        let secret = SecretString::from(value);
        set_gateway_secret_impl(&scope, &key_name, &secret).map_err(ServerFnError::new)
    }
    #[cfg(target_arch = "wasm32")]
    {
        let _ = (scope, key_name, value);
        unreachable!("server fn body never runs on the wasm client")
    }
}

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
    use super::*;
    use ironhermes_core::config::{Config, SecurityConfig};

    fn seeded_config(write_enabled: bool) -> Config {
        Config {
            security: SecurityConfig {
                web_config_write_enabled: write_enabled,
                ..Default::default()
            },
            ..Config::default()
        }
    }

    /// Recursively walk a serialized JSON value and assert none of the
    /// secret-bearing key names appears at ANY nesting depth — mirrors
    /// `platform_config_api::tests::assert_no_secret_key_at_any_depth`
    /// (test-only duplication across modules is the established precedent
    /// in this crate; neither module exports its copy).
    fn assert_no_secret_key_at_any_depth(value: &serde_json::Value) {
        match value {
            serde_json::Value::Object(map) => {
                for forbidden in ["value", "token", "app_token", "api_key", "secret"] {
                    assert!(
                        !map.contains_key(forbidden),
                        "serialized DTO must never carry a field named '{forbidden}' at any nesting depth"
                    );
                }
                for v in map.values() {
                    assert_no_secret_key_at_any_depth(v);
                }
            }
            serde_json::Value::Array(items) => {
                for v in items {
                    assert_no_secret_key_at_any_depth(v);
                }
            }
            _ => {}
        }
    }

    // -------------------------------------------------------------------
    // Task 1 — root-scope write-only writer.
    // -------------------------------------------------------------------

    #[test]
    fn root_scope_write_creates_key_single_quoted_at_0600_and_preserves_existing_key() {
        use std::os::unix::fs::PermissionsExt;

        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(true).save().expect("seed root config.yaml");

        // Pre-existing unrelated key must survive the write untouched.
        let env_path = ironhermes_core::config::Config::env_path();
        let pre_existing = vec![("UNRELATED_KEY".to_string(), "keep-me".to_string())];
        let pre_contents =
            render_root_env_with_stamp("root", &pre_existing).expect("render pre-existing .env");
        crate::server::profile_api::write_env_atomic_0600(&env_path, &pre_contents)
            .expect("seed pre-existing .env");

        let secret = SecretString::from("s3cr3t-val".to_string());
        let result = set_gateway_secret_impl(
            &ConfigScope::Root,
            "IRONHERMES_API_SERVER_KEY",
            &secret,
        );

        let raw = std::fs::read_to_string(&env_path).expect("read written .env");
        let meta = std::fs::metadata(&env_path).expect("stat written .env");
        let env_map =
            crate::server::profile_api::read_env_keys(&env_path).expect("parse written .env");
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        let ack = result.expect("root-scope write must succeed");
        assert_eq!(ack.key_name, "IRONHERMES_API_SERVER_KEY");
        assert!(ack.present);
        assert!(
            raw.contains("IRONHERMES_API_SERVER_KEY='s3cr3t-val'"),
            "value must be written single-quoted; got:\n{raw}"
        );
        assert_eq!(
            meta.permissions().mode() & 0o777,
            0o600,
            "written .env must be mode 0600"
        );
        assert_eq!(
            env_map.get("UNRELATED_KEY").map(String::as_str),
            Some("keep-me"),
            "a pre-existing unrelated key must survive the write"
        );
    }

    #[test]
    fn set_gateway_secret_ack_never_contains_the_secret_value() {
        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(true).save().expect("seed root config.yaml");

        const SENTINEL: &str = "sk-T49-3-02-CANARY-must-never-surface";
        let secret = SecretString::from(SENTINEL.to_string());
        let result = set_gateway_secret_impl(&ConfigScope::Root, "IRONHERMES_API_SERVER_KEY", &secret);
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        let ack = result.expect("write must succeed");
        let json = serde_json::to_value(&ack).expect("DTO must serialize");
        assert_no_secret_key_at_any_depth(&json);
        assert!(
            !json.to_string().contains(SENTINEL),
            "serialized DTO must never contain the raw secret value"
        );
    }

    #[test]
    fn profile_scope_write_delegates_and_leaves_root_env_untouched() {
        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(true).save().expect("seed root config.yaml");
        std::fs::create_dir_all(crate::server::profile_api::profile_dir_for("bot-profile"))
            .expect("create profile dir");

        let root_env_path = ironhermes_core::config::Config::env_path();
        assert!(
            !root_env_path.exists(),
            "root .env must not exist before the profile-scope write"
        );

        let secret = SecretString::from("tg-bot-token".to_string());
        let result = set_gateway_secret_impl(
            &ConfigScope::Profile("bot-profile".to_string()),
            "TELEGRAM_BOT_TOKEN",
            &secret,
        );

        let root_env_exists_after = root_env_path.exists();
        let profile_env_map = crate::server::profile_api::read_env_keys(
            &crate::server::profile_api::profile_dir_for("bot-profile").join(".env"),
        )
        .expect("parse profile .env");
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        let ack = result.expect("profile-scope write must succeed");
        assert_eq!(ack.key_name, "TELEGRAM_BOT_TOKEN");
        assert!(ack.present);
        assert!(
            !root_env_exists_after,
            "a profile-scope write must never create/touch the root .env"
        );
        assert_eq!(
            profile_env_map.get("TELEGRAM_BOT_TOKEN").map(String::as_str),
            Some("tg-bot-token")
        );
    }

    // -------------------------------------------------------------------
    // Task 2 — adversarial hardening (env-name injection, quote-escaping,
    // gate fail-closed, no-value-leak).
    // -------------------------------------------------------------------

    #[test]
    fn env_name_injection_is_rejected_before_any_write() {
        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(true).save().expect("seed root config.yaml");
        let env_path = ironhermes_core::config::Config::env_path();
        assert!(!env_path.exists(), "no .env must exist before either rejected write");

        let secret = SecretString::from("value".to_string());

        // A newline-bearing name could otherwise forge a second VAR=value
        // line (T-49.3-02-01).
        let newline_result =
            set_gateway_secret_impl(&ConfigScope::Root, "FOO\nBAR", &secret);
        assert!(
            newline_result.is_err(),
            "a newline-bearing key name must be rejected"
        );
        assert!(
            !env_path.exists(),
            "a rejected newline-bearing name must never touch the .env file"
        );

        // A lowercase name is also rejected by validate_key_name's
        // [A-Z][A-Z0-9_]* rule.
        let lowercase_result = set_gateway_secret_impl(&ConfigScope::Root, "foo", &secret);
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        assert!(
            lowercase_result.is_err(),
            "a lowercase key name must be rejected"
        );
        assert!(
            !env_path.exists(),
            "a rejected lowercase name must never touch the .env file"
        );
    }

    #[test]
    fn value_containing_dollar_brace_quote_and_trailing_backslash_round_trips_literally() {
        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(true).save().expect("seed root config.yaml");

        // Exercises dollar-substitution suppression, an embedded single
        // quote, and a trailing backslash (the two-stage dotenvy
        // parser/writer boundary from project memory) in one value.
        const ADVERSARIAL_VALUE: &str = r"${HOME}/it's-mine\";
        let secret = SecretString::from(ADVERSARIAL_VALUE.to_string());
        let result = set_gateway_secret_impl(&ConfigScope::Root, "ADVERSARIAL_KEY", &secret);

        let env_path = ironhermes_core::config::Config::env_path();
        let env_map =
            crate::server::profile_api::read_env_keys(&env_path).expect("parse written .env");
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        result.expect("adversarial value write must succeed");
        assert_eq!(
            env_map.get("ADVERSARIAL_KEY").map(String::as_str),
            Some(ADVERSARIAL_VALUE),
            "the exact literal must round-trip — no ${{}} substitution, no merged line"
        );
    }

    #[test]
    fn write_refuses_when_gate_closed_before_touching_the_env_file() {
        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(false).save().expect("seed root config.yaml with writes disabled");
        let env_path = ironhermes_core::config::Config::env_path();
        assert!(!env_path.exists(), "no .env must exist before the refused write");

        let secret = SecretString::from("value".to_string());
        let result = set_gateway_secret_impl(&ConfigScope::Root, "IRONHERMES_API_SERVER_KEY", &secret);
        let exists_after = env_path.exists();
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        assert!(result.is_err(), "write must be refused when the gate is closed");
        assert!(!exists_after, "a refused write must never create the .env file");
    }

    #[test]
    fn no_value_leak_serialized_ack_never_carries_the_secret() {
        let _g = crate::server::test_support::env_lock();
        let home_dir = tempfile::tempdir().expect("tempdir");
        unsafe { std::env::set_var("IRONHERMES_HOME", home_dir.path()) };

        seeded_config(true).save().expect("seed root config.yaml");

        const SENTINEL: &str = "sk-T49-3-02-TASK2-CANARY";
        let secret = SecretString::from(SENTINEL.to_string());
        let result = set_gateway_secret_impl(&ConfigScope::Root, "IRONHERMES_API_SERVER_KEY", &secret);
        unsafe { std::env::remove_var("IRONHERMES_HOME") };

        let ack = result.expect("write must succeed");
        let json = serde_json::to_value(&ack).expect("DTO must serialize");
        assert_no_secret_key_at_any_depth(&json);
        assert!(
            !json.to_string().contains(SENTINEL),
            "serialized DTO must never contain the raw secret value at any depth"
        );
    }
}
