pub mod client;
pub mod agent_loop;
pub mod budget;
pub mod memory;
pub mod session_search;
pub mod context_loader;
pub mod prompt_builder;
pub mod personality;
pub mod subdir_discovery;
pub mod context_compressor;
pub mod context_engine;
pub mod tool_pair;
pub mod summarizing_engine;
pub mod memory_flush_handler;
pub mod pressure_warning;
pub mod engine_factory;
pub mod agent_wiring;
pub mod subagent_runner;
pub mod subagent_registry;
pub mod transcript;
pub mod anthropic_client;
pub mod any_client;

pub use agent_loop::{AgentLoop, AgentResult, AggregatedUsage};
pub use memory::{MemoryManager, SharedProvider};
pub use client::LlmClient;
pub use anthropic_client::AnthropicClient;
pub use any_client::{AnyClient, AnyClientVisionHandle, build_client, build_main_client, build_role_client};
pub use prompt_builder::{PromptBuilder, PromptSlot};
pub use personality::PersonalityRegistry;
pub use context_compressor::ContextCompressor;
pub use agent_wiring::attach_context_engine;
pub use pressure_warning::PressureTracker;
pub use subagent_runner::AgentSubagentRunner;
pub use ironhermes_core::{scan_context_content, truncate_content, CONTEXT_FILE_MAX_CHARS};
